# -*- coding: utf-8 -*-
"""Ecrit les quatre fichiers de langue depuis une table unique.

Une table et non quatre fichiers tenus a la main : c'est la seule facon de
voir d'un coup d'oeil qu'une traduction manque ou qu'elle a derive de
l'original. Le fichier genere, lui, reste du Dart ordinaire et lisible.
"""
import io
import os

# clef -> (parametres ou None, fr, en, es, pt)
# Les parametres sont ceux declares dans textes.dart.
TABLE = [
    ('# commun', None, None, None, None, None),
    ('marque', None, 'DTracker', 'DTracker', 'DTracker', 'DTracker'),
    ('pause', None, 'Pause', 'Pause', 'Pausa', 'Pausa'),
    ('reprendre', None, 'Reprendre', 'Resume', 'Reanudar', 'Retomar'),
    ('reset', None, 'Reset', 'Reset', 'Reiniciar', 'Reiniciar'),
    ('resetInfobulle', None,
     'Clore cette session et en ouvrir une neuve',
     'Close this session and start a new one',
     'Cerrar esta sesión y abrir una nueva',
     'Encerrar esta sessão e abrir uma nova'),
    ('quitter', None, 'Quitter', 'Quit', 'Salir', 'Sair'),
    ('sessions', None, 'Sessions', 'Sessions', 'Sesiones', 'Sessões'),
    ('reglages', None, 'Réglages', 'Settings', 'Ajustes', 'Configurações'),
    ('vueCompacte', None,
     'Passer en vue compacte', 'Switch to compact view',
     'Cambiar a vista compacta', 'Mudar para a vista compacta'),
    ('vueComplete', None,
     'Revenir à la vue complète', 'Back to full view',
     'Volver a la vista completa', 'Voltar à vista completa'),
    ('renommerSession', None,
     'Cliquer pour renommer la session', 'Click to rename the session',
     'Haz clic para renombrar la sesión', 'Clique para renomear a sessão'),
    ('fenetreBloquee', None,
     'Fenêtre bloquée — cliquer pour pouvoir la déplacer',
     'Window locked — click to be able to move it',
     'Ventana bloqueada — haz clic para poder moverla',
     'Janela bloqueada — clique para poder movê-la'),
    ('fenetreLibre', None,
     'Fenêtre libre — la saisir n\\\'importe où la déplace',
     'Window unlocked — grab it anywhere to move it',
     'Ventana libre — agárrala en cualquier punto para moverla',
     'Janela livre — segure-a em qualquer ponto para movê-la'),
    ('enPause', None, 'en pause', 'paused', 'en pausa', 'em pausa'),
    ('enCours', None, 'en cours', 'running', 'en curso', 'em curso'),
    ('sessionNumero', 'int numero',
     'Session $numero', 'Session $numero', 'Sesión $numero', 'Sessão $numero'),

    ('# colonnes', None, None, None, None, None),
    ('colPersonnage', None, 'PERSONNAGE', 'CHARACTER', 'PERSONAJE', 'PERSONAGEM'),
    ('colNiveau', None, 'NIVEAU', 'LEVEL', 'NIVEL', 'NÍVEL'),
    ('colExperience', None, 'EXPÉRIENCE', 'EXPERIENCE', 'EXPERIENCIA',
     'EXPERIÊNCIA'),
    ('colButin', None, 'BUTIN', 'LOOT', 'BOTÍN', 'ESPÓLIO'),
    ('colObjets', None, 'OBJETS', 'ITEMS', 'OBJETOS', 'ITENS'),
    ('colCombats', None, 'COMBATS', 'FIGHTS', 'COMBATES', 'COMBATES'),
    ('colChallenges', None, 'CHALLENGES', 'CHALLENGES', 'DESAFÍOS', 'DESAFIOS'),
    ('colDuree', None, 'DURÉE', 'DURATION', 'DURACIÓN', 'DURAÇÃO'),
    ('colFinDuCombat', None, 'FIN DU COMBAT', 'FIGHT ENDED', 'FIN DEL COMBATE',
     'FIM DO COMBATE'),
    ('colTotal', None, 'TOTAL', 'TOTAL', 'TOTAL', 'TOTAL'),
    ('colXp', None, 'XP', 'XP', 'XP', 'XP'),
    ('colPrix', None, 'PRIX MOYEN', 'AVG. PRICE', 'PRECIO MEDIO',
     'PREÇO MÉDIO'),
    ('colQuantite', None, 'QUANTITÉ', 'QUANTITY', 'CANTIDAD', 'QUANTIDADE'),
    ('colPoids', None, 'POIDS', 'WEIGHT', 'PESO', 'PESO'),
    ('colType', None, 'TYPE', 'TYPE', 'TIPO', 'TIPO'),

    ('# navigation', None, None, None, None, None),
    ('suivi', None, 'Suivi', 'Overview', 'Resumen', 'Resumo'),
    ('suiviSousTitre', None,
     'Suivi de la session en cours', 'Current session overview',
     'Resumen de la sesión en curso', 'Resumo da sessão em curso'),
    ('mesCombats', None, 'Mes combats', 'My fights', 'Mis combates',
     'Os meus combates'),
    ('mesCombatsSousTitre', None,
     'Les combats de la session, du plus récent au plus ancien',
     'This session\\\'s fights, newest first',
     'Los combates de la sesión, del más reciente al más antiguo',
     'Os combates da sessão, do mais recente ao mais antigo'),
    ('monInventaire', None, 'Mon inventaire', 'My inventory', 'Mi inventario',
     'O meu inventário'),
    ('monInventaireSousTitre', None,
     'Tout ce que le groupe a ramassé', 'Everything the party picked up',
     'Todo lo que el grupo ha recogido', 'Tudo o que o grupo apanhou'),
    ('sessionsSousTitre', None,
     'Liste des sessions enregistrées', 'List of saved sessions',
     'Lista de las sesiones guardadas', 'Lista das sessões guardadas'),
    ('reglagesSousTitre', None,
     'Ce que l\\\'outil suit, et comment il s\\\'affiche',
     'What the tool tracks, and how it looks',
     'Lo que la herramienta sigue, y cómo se muestra',
     'O que a ferramenta segue, e como se apresenta'),
    ('butinDe', 'String personnage',
     'Butin de $personnage', '$personnage\\\'s loot', 'Botín de $personnage',
     'Espólio de $personnage'),
    ('finDuCombat', None, 'Fin du combat', 'Fight ended', 'Fin del combate',
     'Fim do combate'),
    ('retour', None, 'Retour', 'Back', 'Volver', 'Voltar'),

    ('# suivi', None, None, None, None, None),
    ('horsCombat', None, 'Hors combat', 'Out of combat', 'Fuera de combate',
     'Fora de combate'),
    ('enCombatDepuis', 'String duree',
     'En combat  ·  $duree', 'In combat  ·  $duree',
     'En combate  ·  $duree', 'Em combate  ·  $duree'),
    ('tour', 'int numero',
     'tour $numero', 'turn $numero', 'turno $numero', 'turno $numero'),
    ('cadenceXp', None, 'xp/h', 'xp/h', 'xp/h', 'xp/h'),
    ('cadenceKamas', None, 'kamas/h', 'kamas/h', 'kamas/h', 'kamas/h'),
    ('aucunPersonnageSuivi', None,
     'Aucun personnage suivi', 'No character tracked',
     'Ningún personaje seguido', 'Nenhum personagem seguido'),
    ('aucunPersonnageDetail', None,
     'Ajoutez-en dans les réglages pour voir leurs gains apparaître ici.',
     'Add some in the settings to see their gains appear here.',
     'Añade alguno en los ajustes para ver sus ganancias aquí.',
     'Adicione alguns nas configurações para ver os ganhos aqui.'),
    ('ouvrirLesReglages', None,
     'Ouvrir les réglages', 'Open the settings', 'Abrir los ajustes',
     'Abrir as configurações'),
    ('enAttenteDuJeu', None,
     'En attente du jeu', 'Waiting for the game', 'Esperando el juego',
     'À espera do jogo'),
    ('aucunNaJoue', 'int suivis',
     'Aucun des $suivis personnages suivis n\\\'a encore joué.',
     'None of the $suivis tracked characters has played yet.',
     'Ninguno de los $suivis personajes seguidos ha jugado todavía.',
     'Nenhum dos $suivis personagens seguidos jogou ainda.'),
    ('progressionInconnue', None,
     'Progression inconnue — aucun état reçu pour ce personnage',
     'Progress unknown — no state received for this character',
     'Progreso desconocido — no se ha recibido estado de este personaje',
     'Progresso desconhecido — nenhum estado recebido deste personagem'),
    ('progression',
     'String dans, String du, String pourcent, String niveau, String gagne',
     '$dans / $du XP\\n$pourcent % du niveau $niveau\\n'
     'dont $gagne gagnés cette session',
     '$dans / $du XP\\n$pourcent % of level $niveau\\n'
     'including $gagne earned this session',
     '$dans / $du XP\\n$pourcent % del nivel $niveau\\n'
     'de los cuales $gagne en esta sesión',
     '$dans / $du XP\\n$pourcent % do nível $niveau\\n'
     'dos quais $gagne nesta sessão'),
    ('cliquerPourCombats', None,
     'Cliquer pour voir ses combats', 'Click to see their fights',
     'Haz clic para ver sus combates', 'Clique para ver os seus combates'),
    ('classeInconnue', None,
     'Classe inconnue — elle apparaîtra au prochain passage sur une carte',
     'Class unknown — it will show up on the next map change',
     'Clase desconocida — aparecerá al pasar por el próximo mapa',
     'Classe desconhecida — aparecerá na próxima mudança de mapa'),
    ('ecarte', None, 'écarté', 'discarded', 'descartado', 'descartado'),
    ('impose', None, 'imposé', 'imposed', 'impuesto', 'imposto'),

    ('# combats', None, None, None, None, None),
    ('aucunCombat', None,
     'Aucun combat sur cette session', 'No fight in this session',
     'Ningún combate en esta sesión', 'Nenhum combate nesta sessão'),
    ('aucunCombatDetail', None,
     'La liste se remplit à la fin de chaque combat.',
     'The list fills up at the end of each fight.',
     'La lista se completa al final de cada combate.',
     'A lista enche-se ao fim de cada combate.'),
    ('gagnants', None, 'GAGNANTS', 'WINNERS', 'GANADORES', 'VENCEDORES'),
    ('perdants', None, 'PERDANTS', 'LOSERS', 'PERDEDORES', 'PERDEDORES'),
    ('adversaireInconnu', None,
     'Adversaire inconnu', 'Unknown opponent', 'Adversario desconocido',
     'Adversário desconhecido'),
    ('personneNaGagne', None,
     'Personne n\\\'a gagné ce combat', 'Nobody won this fight',
     'Nadie ganó este combate', 'Ninguém ganhou este combate'),
    ('nbCombats', 'int n',
     '$n combats', '$n fights', '$n combates', '$n combates'),

    ('# inventaire', None, None, None, None, None),
    ('aucunItem', None,
     'Aucun item trouvé dans l\\\'inventaire de la session',
     'No item found in this session\\\'s inventory',
     'Ningún objeto en el inventario de la sesión',
     'Nenhum item no inventário da sessão'),
    ('triAucun', None, 'Aucun tri', 'No sorting', 'Sin orden', 'Sem ordenação'),
    ('triNom', None, 'Trier par nom', 'Sort by name', 'Ordenar por nombre',
     'Ordenar por nome'),
    ('triPoids', None, 'Trier par poids', 'Sort by weight',
     'Ordenar por peso', 'Ordenar por peso'),
    ('triPoidsLot', None, 'Trier par poids du lot', 'Sort by stack weight',
     'Ordenar por peso del lote', 'Ordenar por peso do lote'),
    ('triQuantite', None, 'Trier par quantité', 'Sort by quantity',
     'Ordenar por cantidad', 'Ordenar por quantidade'),
    ('triPrix', None, 'Trier par prix moyen', 'Sort by average price',
     'Ordenar por precio medio', 'Ordenar por preço médio'),
    ('triPrixLot', None, 'Trier par prix moyen du lot',
     'Sort by average stack price', 'Ordenar por precio medio del lote',
     'Ordenar por preço médio do lote'),
    ('prixNonDisponible', None,
     'Prix non disponible', 'Price not available', 'Precio no disponible',
     'Preço indisponível'),
    ('lot', None, 'Lot', 'Stack', 'Lote', 'Lote'),
    ('unitaire', None, 'Unitaire', 'Unit', 'Unidad', 'Unidade'),
    ('valeurEstimee', None,
     'Valeur estimée des ressources', 'Estimated value of resources',
     'Valor estimado de los recursos', 'Valor estimado dos recursos'),
    ('kamasEnPiece', None,
     'Kamas en pièce', 'Kamas in coin', 'Kamas en monedas',
     'Kamas em moedas'),

    ('# sessions', None, None, None, None, None),
    ('aucuneSession', None,
     'Aucune session enregistrée', 'No saved session',
     'Ninguna sesión guardada', 'Nenhuma sessão guardada'),
    ('aucuneSessionDetail', None,
     'La session en cours y figurera dès son premier gain.',
     'The current session will show up on its first gain.',
     'La sesión en curso aparecerá con su primera ganancia.',
     'A sessão em curso aparecerá no seu primeiro ganho.'),
    ('dureeEcoute', 'String duree',
     '$duree d\\\'écoute', '$duree of listening', '$duree de escucha',
     '$duree de escuta'),
    ('dureeEcouteReprises', 'String duree, int reprises',
     '$duree d\\\'écoute, en $reprises reprises\\n'
     'Les nuits et les pauses n\\\'y sont pas comptées.',
     '$duree of listening, over $reprises runs\\n'
     'Nights and pauses are not counted.',
     '$duree de escucha, en $reprises tramos\\n'
     'Las noches y las pausas no se cuentan.',
     '$duree de escuta, em $reprises retomas\\n'
     'As noites e as pausas não são contadas.'),
    ('nbReprises', 'int n',
     '$n reprises', '$n runs', '$n tramos', '$n retomas'),
    ('reprendreSession', None,
     'Reprendre cette session : elle redevient la session en cours',
     'Resume this session: it becomes the current one again',
     'Reanudar esta sesión: vuelve a ser la sesión en curso',
     'Retomar esta sessão: volta a ser a sessão em curso'),
    ('supprimerSession', None,
     'Supprimer cette session', 'Delete this session',
     'Eliminar esta sesión', 'Eliminar esta sessão'),
    ('supprimerConfirme', None,
     'Cette session sera effacée définitivement.',
     'This session will be permanently deleted.',
     'Esta sesión se borrará definitivamente.',
     'Esta sessão será apagada definitivamente.'),
    ('annuler', None, 'Annuler', 'Cancel', 'Cancelar', 'Cancelar'),
    ('supprimer', None, 'Supprimer', 'Delete', 'Eliminar', 'Eliminar'),

    ('# reglages', None, None, None, None, None),
    ('ongletPersonnages', None, 'Personnages', 'Characters', 'Personajes',
     'Personagens'),
    ('ongletPersonnagesAvecNombre', 'int n',
     'Personnages ($n)', 'Characters ($n)', 'Personajes ($n)',
     'Personagens ($n)'),
    ('ongletComptage', None, 'Comptage', 'Counting', 'Recuento', 'Contagem'),
    ('ongletCapture', None, 'Capture', 'Capture', 'Captura', 'Captura'),
    ('ongletFenetre', None, 'Fenêtre', 'Window', 'Ventana', 'Janela'),
    ('ongletLangue', None, 'Langue', 'Language', 'Idioma', 'Idioma'),
    ('nomDuPersonnage', None, 'Nom du personnage', 'Character name',
     'Nombre del personaje', 'Nome do personagem'),
    ('ajouter', None, 'Ajouter', 'Add', 'Añadir', 'Adicionar'),
    ('retirer', None,
     'Retirer — ses compteurs sont effacés',
     'Remove — its counters are cleared',
     'Quitar — sus contadores se borran',
     'Remover — os seus contadores são apagados'),
    ('compterLesSucces', None, 'Compter les succès', 'Count achievements',
     'Contar los logros', 'Contar as conquistas'),
    ('compterLesSuccesDetail', None,
     'L\\\'expérience, les kamas et les ressources liés aux succès seront\\n'
     'comptabilisés dans la session.',
     'Experience, kamas and resources from achievements will be\\n'
     'counted in the session.',
     'La experiencia, los kamas y los recursos de los logros se\\n'
     'contarán en la sesión.',
     'A experiência, os kamas e os recursos das conquistas serão\\n'
     'contados na sessão.'),
    ('interfaceEcoute', None,
     'INTERFACE D\\\'ÉCOUTE RÉSEAU', 'NETWORK CAPTURE INTERFACE',
     'INTERFAZ DE ESCUCHA DE RED', 'INTERFACE DE ESCUTA DE REDE'),
    ('toutesLesInterfaces', None,
     'Toutes les interfaces', 'All interfaces', 'Todas las interfaces',
     'Todas as interfaces'),
    ('toutesLesInterfacesRecommande', None,
     'Toutes les interfaces (recommandé)', 'All interfaces (recommended)',
     'Todas las interfaces (recomendado)',
     'Todas as interfaces (recomendado)'),
    ('introuvable', 'String valeur',
     '$valeur (introuvable)', '$valeur (not found)',
     '$valeur (no encontrada)', '$valeur (não encontrada)'),
    ('toujoursDevant', None,
     'Toujours au premier plan', 'Always on top', 'Siempre delante',
     'Sempre à frente'),
    ('transparence', None,
     'TRANSPARENCE DE LA VUE COMPACTE', 'COMPACT VIEW TRANSPARENCY',
     'TRANSPARENCIA DE LA VISTA COMPACTA',
     'TRANSPARÊNCIA DA VISTA COMPACTA'),
    ('transparenceDetail', None,
     'Le fond ne peut pas être plus opaque que le texte.',
     'The background cannot be more opaque than the text.',
     'El fondo no puede ser más opaco que el texto.',
     'O fundo não pode ser mais opaco que o texto.'),
    ('fond', None, 'Fond', 'Background', 'Fondo', 'Fundo'),
    ('texte', None, 'Texte', 'Text', 'Texto', 'Texto'),
    ('apercu', None, 'APERÇU', 'PREVIEW', 'VISTA PREVIA', 'PRÉ-VISUALIZAÇÃO'),
    ('langue', None, 'LANGUE', 'LANGUAGE', 'IDIOMA', 'IDIOMA'),
    ('langueDetail', None,
     'Le changement prend effet aussitôt.', 'The change takes effect at once.',
     'El cambio surte efecto de inmediato.',
     'A alteração tem efeito imediato.'),

    ('# flux', None, None, None, None, None),
    ('fluxConnecte', None, 'Connecté', 'Connected', 'Conectado', 'Ligado'),
    ('fluxEnAttente', None, 'En attente du jeu', 'Waiting for the game',
     'Esperando el juego', 'À espera do jogo'),
    ('fluxInjoignable', None, 'Capture injoignable', 'Capture unreachable',
     'Captura inalcanzable', 'Captura inacessível'),
    ('fluxIndisponible', None, 'Capture indisponible', 'Capture unavailable',
     'Captura no disponible', 'Captura indisponível'),
    ('fluxDeconnecte', None, 'Déconnecté', 'Disconnected', 'Desconectado',
     'Desligado'),
    ('diagEcouteSur', 'String carte',
     'Les événements du jeu arrivent.\\nÉcoute sur $carte.',
     'Game events are coming in.\\nListening on $carte.',
     'Los eventos del juego están llegando.\\nEscuchando en $carte.',
     'Os eventos do jogo estão a chegar.\\nA escutar em $carte.'),
    ('diagRienEntendu', 'String carte',
     'La capture tourne et répond, mais n\\\'a encore rien entendu.\\n'
     'Écoute sur $carte.\\n\\nNormal si aucun personnage n\\\'est connecté. '
     'Si le jeu tourne, c\\\'est\\nque la carte écoutée ne porte pas son '
     'trafic : réglez-la sur\\n« Toutes les interfaces », dans Réglages.',
     'The capture is running and answering, but has heard nothing yet.\\n'
     'Listening on $carte.\\n\\nNormal if no character is connected. If the '
     'game is running,\\nthe listened card does not carry its traffic: set it '
     'to\\n"All interfaces", in Settings.',
     'La captura funciona y responde, pero aún no ha oído nada.\\n'
     'Escuchando en $carte.\\n\\nNormal si ningún personaje está conectado. '
     'Si el juego funciona,\\nla tarjeta escuchada no lleva su tráfico: '
     'ponla en\\n«Todas las interfaces», en Ajustes.',
     'A captura funciona e responde, mas ainda não ouviu nada.\\n'
     'A escutar em $carte.\\n\\nNormal se nenhum personagem estiver ligado. '
     'Se o jogo corre,\\na placa escutada não transporta o seu tráfego: '
     'defina-a para\\n«Todas as interfaces», nas Configurações.',
     ),
    ('diagNeRepondPas', None,
     "La diffusion ne répond pas encore.\n\nElle démarre — quelques secondes — ou elle s'est arrêtée en chemin.\nLa liaison se rétablit d'elle-même dès qu'elle répond.",
     'The stream is not answering yet.\n\nIt is starting up — a few seconds — or it stopped along the way.\nThe link re-establishes itself as soon as it answers.',
     'La difusión aún no responde.\n\nEstá arrancando — unos segundos — o se ha detenido por el camino.\nEl enlace se restablece solo en cuanto responda.',
     'A difusão ainda não responde.\n\nEstá a arrancar — alguns segundos — ou parou pelo caminho.\nA ligação restabelece-se sozinha assim que responder.'),
    ('diagNaPasDemarre', None,
     "La capture n'a pas pu démarrer.\\nLe pilote npcap manque à l'appel.",
     'The capture could not start.\\nThe npcap driver is missing.',
     'La captura no ha podido arrancar.\\nFalta el controlador npcap.',
     'A captura não conseguiu arrancar.\\nFalta o controlador npcap.'),
    ('diagAucuneCapture', None,
     'Aucune capture en cours.', 'No capture running.',
     'Ninguna captura en curso.', 'Nenhuma captura em curso.'),
    ('carteToutesPhysiques', None,
     'toutes les interfaces physiques', 'all physical interfaces',
     'todas las interfaces físicas', 'todas as interfaces físicas'),
    ('carteNommee', 'String nom',
     'l\\\'interface $nom', 'the $nom interface', 'la interfaz $nom',
     'a interface $nom'),
    ('# reste', None, None, None, None, None),
    ('xp', None,
     'XP',
     'XP',
     'XP',
     'XP'),
    ('aucunPersonnageCompacte', None,
     'Aucun personnage suivi — passez en vue complète pour en ajouter',
     'No character tracked — switch to full view to add some',
     'Ningún personaje seguido — pasa a la vista completa para añadir',
     'Nenhum personagem seguido — passe à vista completa para adicionar'),
    ('enAttenteCompacte', 'int suivis',
     "En attente : aucun des $suivis personnages suivis n\\'a encore joué",
     'Waiting: none of the $suivis tracked characters has played yet',
     'Esperando: ninguno de los $suivis personajes seguidos ha jugado',
     'À espera: nenhum dos $suivis personagens seguidos jogou ainda'),
    ('suiviOnglet', None,
     'Le tableau des personnages',
     'The character table',
     'La tabla de los personajes',
     'A tabela dos personagens'),
    ('mesCombatsOnglet', None,
     'Tous les combats de la session',
     "All the session\\'s fights",
     'Todos los combates de la sesión',
     'Todos os combates da sessão'),
    ('monInventaireOnglet', None,
     'Le butin du groupe, personnage par personnage',
     "The party\\'s loot, character by character",
     'El botín del grupo, personaje por personaje',
     'O espólio do grupo, personagem por personagem'),
    ('sonButin', None,
     'Son butin sur cette session',
     'Their loot in this session',
     'Su botín en esta sesión',
     'O seu espólio nesta sessão'),
    ('termineLe', None,
     'TERMINÉ LE',
     'ENDED ON',
     'TERMINADO EL',
     'TERMINADO EM'),
    ('combatDejaCommence', None,
     "Le combat avait commencé avant que l\\'outil n\\'écoute.\\nLe récapitulatif ne nomme pas les adversaires.",
     'The fight had started before the tool was listening.\\nThe summary does not name the opponents.',
     'El combate había empezado antes de que la herramienta escuchara.\\nEl resumen no nombra a los adversarios.',
     'O combate começara antes de a ferramenta escutar.\\nO resumo não nomeia os adversários.'),
    ('reussi', None,
     'réussi',
     'passed',
     'logrado',
     'conseguido'),
    ('echoue', None,
     'échoué',
     'failed',
     'fallado',
     'falhado'),
    ('nbObjets', 'int n',
     '$n objets',
     '$n items',
     '$n objetos',
     '$n itens'),
    ('surTotal', 'int retenus, int total',
     '$retenus sur $total',
     '$retenus of $total',
     '$retenus de $total',
     '$retenus de $total'),
    ('inventaire', None,
     'INVENTAIRE',
     'INVENTORY',
     'INVENTARIO',
     'INVENTÁRIO'),
    ('gainsComptesDetail', None,
     'Les gains ne sont comptés que pour les personnages\\nlistés ici — les vôtres, et ceux de vos amis si vous voulez suivre le groupe.',
     "Gains are only counted for the characters listed here — yours,\\nand your friends\\' if you want to follow the party.",
     'Las ganancias solo se cuentan para los personajes listados aquí — los tuyos,\\ny los de tus amigos si quieres seguir al grupo.',
     'Os ganhos só são contados para os personagens listados aqui — os seus,\\ne os dos seus amigos se quiser seguir o grupo.'),
    ('portraitIntrouvable', 'String classe',
     '$classe — portrait introuvable, les images ont-elles été extraites ?',
     '$classe — portrait not found, have the images been extracted?',
     '$classe — retrato no encontrado, ¿se han extraído las imágenes?',
     '$classe — retrato não encontrado, as imagens foram extraídas?'),
    ('classeNumero', 'int classe',
     'Classe $classe',
     'Class $classe',
     'Clase $classe',
     'Classe $classe'),
    ('# sessions et butin', None, None, None, None, None),
    ('colSession', None,
     'SESSION',
     'SESSION',
     'SESIÓN',
     'SESSÃO'),
    ('enregistrees', None,
     'ENREGISTRÉES',
     'SAVED',
     'GUARDADAS',
     'GUARDADAS'),
    ('valeur', None,
     'VALEUR',
     'VALUE',
     'VALOR',
     'VALOR'),
    ('enPiece', None,
     'EN PIÈCE',
     'IN COIN',
     'EN MONEDAS',
     'EM MOEDAS'),
    ('valeurRessources', None,
     'VALEUR ESTIMÉE DES RESSOURCES',
     'ESTIMATED VALUE OF RESOURCES',
     'VALOR ESTIMADO DE LOS RECURSOS',
     'VALOR ESTIMADO DOS RECURSOS'),
    ('butinComplet', None,
     'Butin complet',
     'Full loot',
     'Botín completo',
     'Espólio completo'),
    ('butinSession', None,
     'Le butin de la session, personnages au choix',
     "The session\\'s loot, characters of your choosing",
     'El botín de la sesión, personajes a elegir',
     'O espólio da sessão, personagens à escolha'),
    ('supprimerCetteSession', None,
     'Supprimer cette session ?',
     'Delete this session?',
     '¿Eliminar esta sesión?',
     'Eliminar esta sessão?'),
    ('resumeSession', 'String combats, String xp, String kamas',
     '$combats combats  ·  $xp xp  ·  $kamas kamas',
     '$combats fights  ·  $xp xp  ·  $kamas kamas',
     '$combats combates  ·  $xp xp  ·  $kamas kamas',
     '$combats combates  ·  $xp xp  ·  $kamas kamas'),
    ('aucuneSessionNaitDetail', None,
     "Une session naît à son premier combat. Lancer l\\'outil puis le fermer\\nne laisse donc aucune trace.",
     'A session is born on its first fight. Starting the tool then closing it\\nleaves no trace.',
     'Una sesión nace en su primer combate. Abrir la herramienta y cerrarla\\nno deja ninguna huella.',
     'Uma sessão nasce no seu primeiro combate. Abrir a ferramenta e fechá-la\\nnão deixa qualquer rasto.'),
    ('reprendreDetail', None,
     'Reprendre cette session : elle redevient la session courante\\net repart aussitôt.',
     'Resume this session: it becomes the current one and starts again\\nright away.',
     'Reanudar esta sesión: vuelve a ser la sesión actual\\ny arranca de inmediato.',
     'Retomar esta sessão: volta a ser a sessão atual\\ne recomeça de imediato.'),
    ('aucunPersonnageSession', None,
     'Aucun personnage sur cette session',
     'No character in this session',
     'Ningún personaje en esta sesión',
     'Nenhum personagem nesta sessão'),
    ('rapport', 'int reussis, int total',
     '$reussis/$total',
     '$reussis/$total',
     '$reussis/$total',
     '$reussis/$total'),
    ('invitePasCompte', 'String nom',
     '$nom ne fait pas partie des personnages suivis.\\nSon expérience et son butin ne sont pas comptés dans la session.',
     '$nom is not one of the tracked characters.\\nTheir experience and loot are not counted in the session.',
     '$nom no está entre los personajes seguidos.\\nSu experiencia y su botín no cuentan en la sesión.',
     '$nom não faz parte dos personagens seguidos.\\nA sua experiência e o seu espólio não contam na sessão.'),
    ('reduire', None,
     'Réduire la fenêtre',
     'Minimise the window',
     'Minimizar la ventana',
     'Minimizar a janela'),
    ('fluxSansPilote', None,
     'npcap manquant',
     'npcap missing',
     'falta npcap',
     'npcap em falta'),
    ('fluxSansCarte', None,
     'Aucune carte à écouter',
     'No card to listen on',
     'Ninguna tarjeta que escuchar',
     'Nenhuma placa para escutar'),
    ('diagSansPilote', None,
     "Le pilote npcap n'est pas installé.\\n\\nLire le trafic réseau se fait dans le noyau de Windows : il y faut un pilote,\\net aucun programme ne peut s'en passer. npcap est gratuit et pèse un\\nmégaoctet ; son installation ne se demande qu'une fois.\\n\\n→ npcap.com",
     'The npcap driver is not installed.\\n\\nReading network traffic happens in the Windows kernel: it takes a driver,\\nand no program can do without one. npcap is free and weighs a megabyte;\\nit only needs installing once.\\n\\n→ npcap.com',
     'El controlador npcap no está instalado.\\n\\nLeer el tráfico de red ocurre en el núcleo de Windows: hace falta un controlador,\\ny ningún programa puede prescindir de él. npcap es gratuito y pesa un\\nmegabyte; solo se instala una vez.\\n\\n→ npcap.com',
     'O controlador npcap não está instalado.\\n\\nLer o tráfego de rede acontece no núcleo do Windows: é preciso um controlador,\\ne nenhum programa o dispensa. O npcap é gratuito e pesa um megabyte;\\nsó se instala uma vez.\\n\\n→ npcap.com'),
    ('diagSansCarte', 'String carte',
     "Le pilote est là, mais aucune carte réseau n'est écoutable.\\nRéglage courant : $carte.\\n\\nChoisissez « Toutes les interfaces » dans Réglages → Capture.",
     'The driver is there, but no network card can be listened on.\\nCurrent setting: $carte.\\n\\nPick « All interfaces » in Settings → Capture.',
     'El controlador está, pero ninguna tarjeta de red es escuchable.\\nAjuste actual: $carte.\\n\\nElige «Todas las interfaces» en Ajustes → Captura.',
     'O controlador está lá, mas nenhuma placa de rede é escutável.\\nDefinição atual: $carte.\\n\\nEscolha «Todas as interfaces» em Configurações → Captura.'),
]

LANGUES = [('fr', 2, 'TextesFr', 'francais'),
           ('en', 3, 'TextesEn', 'anglais'),
           ('es', 4, 'TextesEs', 'espagnol'),
           ('pt', 5, 'TextesPt', 'portugais')]

os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

for code, colonne, classe, nom in LANGUES:
    lignes = [
        f"/// Les textes en {nom}.",
        "///",
        "/// Genere par `tools/langues.py` : corriger la table plutot que ce",
        "/// fichier, sans quoi la correction sera perdue au prochain passage.",
        "library;",
        "",
        "import 'textes.dart';",
        "",
        f"class {classe} extends Textes {{",
        f"  const {classe}();",
        "",
    ]
    for entree in TABLE:
        clef = entree[0]
        if clef.startswith('#'):
            titre = clef[2:]
            tiret = '-' * max(2, 72 - len(titre) - 6)
            lignes.append(f"  // {tiret} {titre}")
            continue
        params = entree[1]
        valeur = entree[colonne]
        assert valeur is not None, f'{classe} : {clef} manque'
        # Les apostrophes sont echappees ici, une fois pour
        # toutes : les ecrire a la main dans la table, c'est les
        # oublier un jour — et une apostrophe nue ferme la chaine
        # Dart au milieu d'une phrase.
        brut = valeur.replace(chr(92) + "'", "'")
        brut = brut.replace(chr(10), chr(92) + "n")
        litteral = "'" + brut.replace("'", chr(92) + "'") + "'"
        if params:
            lignes.append("  @override")
            lignes.append(f"  String {clef}({params}) => {litteral};")
        else:
            lignes.append("  @override")
            lignes.append(f"  String get {clef} => {litteral};")
        lignes.append("")
    lignes.append("}")
    io.open(f'lib/i18n/{code}.dart', 'w', encoding='utf-8',
            newline='\n').write('\n'.join(lignes) + '\n')
    print(f'lib/i18n/{code}.dart')

nb = len([e for e in TABLE if not e[0].startswith('#')])
print(f'{nb} textes x 4 langues')
